### ISSUE TITLE
spyder-notebook crashed after opening a second new notebook and closing it

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder-notebook#119]
@rmaurer-sfly commented on [Tue Oct 10 2017](https://github.com/spyder-ide/spyder/issues/5435)

## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\rmaurer\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 372, in close_client
    client.shutdown_kernel()
  File "C:\Users\rmaurer\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder_notebook\widgets\client.py", line 236, in shutdown_kernel
    Traceback (most recent call last):
  File "C:\Users\rmaurer\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 372, in close_client
    client.shutdown_kernel()
  File "C:\Users\rmaurer\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder_notebook\widgets\client.py", line 236, in shutdown_kernel
    kernel_id = self.get_kernel_id()
  File "C:\Users\rmaurer\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder_notebook\widgets\client.py", line 230, in get_kernel_id
    if session['notebook']['path'] == path:
KeyError: 'notebook'
kernel_id = self.get_kernel_id()
  File "C:\Users\rmaurer\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder_notebook\widgets\client.py", line 230, in get_kernel_id
    if session['notebook']['path'] == path:
KeyError: 'notebook'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.1
*

**Comment by dalthviz** [comment]
Hi @rmaurer-sfly what version of Jupyter Notebook are you using?

**Comment by rmaurer-sfly** [comment]
Hi,

Notebook version 5.0.0

Sorry for the delayed response – was on vacation

Thanks,
Ron

**Comment by jitseniesen** [comment]
This is the same error message as issue #153 so I'm closing this issue and will work on the other one.
