### ISSUE TITLE
Notebook pane doesn't appear

### ISSUE THREAD

**Issue by cliffckerr** [spyder-ide/spyder-notebook#390]
Depending on the versions of Spyder and other packages, I'm having two problems -- in one case the notebook option doesn't appear at all, with the other the panel appears but the notebooks don't work. I'll describe the issue where they don't appear since that seems to affect the current versions.

Potentially related to https://github.com/spyder-ide/spyder-notebook/issues/386, although the steps there didn't fix it for me.

**What steps will reproduce the problem?**

1. Download and install a fresh Anaconda instance (currently `Anaconda3-2022.10-Linux-x86_64.sh`)
2. Install the notebook plugin as per instructions: `conda install spyder-notebook -c spyder-ide`
5. Run Spyder from the terminal: `spyder`

**What is the expected output? What do you see instead?**

Expect to see a "Notebook" option in View > Panes, but it's not there, `spyder-notebook` isn't listed as one of the dependencies, and the notebook server isn't running.

Trying to import the package from the IPython console within Spyder fails with:

```py
import spyder_notebook
Traceback (most recent call last):

  File "/tmp/ipykernel_50282/1627363730.py", line 1, in <module>
    import spyder_notebook

  File "/software/anaconda/lib/python3.9/site-packages/spyder_notebook/__init__.py", line 11, in <module>
    from spyder_notebook.notebookplugin import NotebookPlugin as PLUGIN_CLASS

  File "/software/anaconda/lib/python3.9/site-packages/spyder_notebook/notebookplugin.py", line 26, in <module>
    from spyder.config.main import CONF

ImportError: cannot import name 'CONF' from 'spyder.config.main' (/software/anaconda/lib/python3.9/site-packages/spyder/config/main.py)
```

If the import line (and the `CONF.set()` line) are commented out in `notebookplugin.py`, then the next error is:

```py
  File "/software/mambaforge/envs/spyder-env/lib/python3.10/site-packages/spyder_notebook/widgets/client.py", line 28, in <module>
    from spyder.config.base import _, get_image_path, get_module_source_path
ImportError: cannot import name 'get_image_path' from 'spyder.config.base' (/software/mambaforge/envs/spyder-env/lib/python3.10/site-packages/spyder/config/base.py)
```

If _these_ lines are commented out in `client.py`, then the import works -- but the Notebook pane still doesn't appear in Spyder.

**Dependencies**

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  63.4.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=3.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.4 (OK)
scipy >=0.17.0                :  1.9.1 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Versions**
```
* Spyder Version: 5.3.3
* Python Version: 3.9.13
* Qt Version: 5.15.2
* PyQt Version: 2.2.0 (qtpy version)
* Jupyter Notebook Version: jupyter_client   : 7.3.4; jupyter_core     : 4.11.1; jupyter_server   : 1.18.1
* Operating system: Ubuntu 22.04 (Linux 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux)
```

**Comment by ccordoba12** [comment]
Hey @cliffckerr, thanks for reporting. You said

> Install the notebook plugin as per instructions: conda install spyder-notebook -c spyder-ide

But [our instructions](https://github.com/spyder-ide/spyder-notebook#installation) clearly say

    conda install spyder-notebook -c conda-forge

So, please try that command and let us know if it works for you.

**Comment by cliffckerr** [comment]
Thanks for the quick reply @ccordoba12 -- I guess that's something else that needs to be updated :)

On https://docs.spyder-ide.org/current/plugins/notebook.html, I'm seeing:
![image](https://user-images.githubusercontent.com/3239256/205102501-caef604e-39a8-479e-8b67-15cb912e665e.png)

When I install with `conda install spyder-notebook -c conda-forge` then I get a different problem: the notebook pane appears and the server starts, but there are no kernels running and the notebook pane is blank (similar to https://github.com/spyder-ide/spyder-notebook/issues/386). If I go to the URL shown in the "Notebook server info" screen, it exists, but without CSS:

```
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
[W 2022-12-01 11:14:26.371 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-12-01 11:14:26.371 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-12-01 11:14:26.375 LabApp] JupyterLab extension loaded from /software/anaconda/lib/python3.9/site-packages/jupyterlab
[I 2022-12-01 11:14:26.375 LabApp] JupyterLab application directory is /software/anaconda/share/jupyter/lab
[I 11:14:26.900 SpyderNotebookServer] Serving notebooks from local directory: /tmp/spyder-cliffk/notebooks
[I 11:14:26.901 SpyderNotebookServer] Jupyter Notebook 6.5.2 is running at:
[I 11:14:26.901 SpyderNotebookServer] http://localhost:8888/?token=e3a8f0eb326c32fe67f97a12089f22426f1bce9586154ed1
[I 11:14:26.901 SpyderNotebookServer]  or http://127.0.0.1:8888/?token=e3a8f0eb326c32fe67f97a12089f22426f1bce9586154ed1
[I 11:14:26.901 SpyderNotebookServer] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:14:26.902 SpyderNotebookServer] 
    
    To access the notebook, open this file in a browser:
        file:///home/cliffk/.local/share/jupyter/runtime/nbserver-78174-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=e3a8f0eb326c32fe67f97a12089f22426f1bce9586154ed1
     or http://127.0.0.1:8888/?token=e3a8f0eb326c32fe67f97a12089f22426f1bce9586154ed1
```

![image](https://user-images.githubusercontent.com/3239256/205103819-50d1f13f-d415-4222-8eaa-7f0840a8cf27.png)
2

which is associated with lots of errors like this (though maybe these are harmless in this mode):
```
[I 11:14:46.612 SpyderNotebookServer] 302 GET /?token=e3a8f0eb326c32fe67f97a12089f22426f1bce9586154ed1 (127.0.0.1) 0.480000ms
[W 11:14:46.656 SpyderNotebookServer] 403 GET /static/components/jquery-ui/dist/themes/smoothness/jquery-ui.min.css?v=32f9dcde0cd9843f2b66d34c1c9928b59a5d7ef007ba7a6a6a790b3e78f7857a698444d7a716dfaf8fa834c3b3175efd258bbc07cfc4aabb86769b07e5f358c3 (127.0.0.1): components/jquery-ui/dist/themes/smoothness/jquery-ui.min.css is not in root static directory
```

**Comment by ccordoba12** [comment]
Ok, then please try with these commands:

    conda create -n spyder-env -c conda-forge python=3.9 spyder spyder-notebook
    conda activate spyder-env
    spyder

Perhaps that works.

**Comment by cliffckerr** [comment]
That did work, thanks!

**Comment by ccordoba12** [comment]
Great! Closing then.

**Comment by ccordoba12** [comment]
Agreed. There's an issue already for that in our documentation repository.
