### ISSUE TITLE
Connection file not found when opening console

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-notebook#421]
When choosing the plugin menu item `Open console`, the following appears in the IPython Console plugin:
```
An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "/home/jitse/spyder/spyder/plugins/ipythonconsole/utils/kernel_handler.py", line 454, in init_kernel_client
kernel_client.load_connection_file()
File "/home/jitse/mambaforge/envs/spynb/lib/python3.11/site‑packages/jupyter_client/connect.py", line 521, in load_connection_file
with open(connection_file) as f:
^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '3ad02cfe‑e528𔂮f8f‑b831�f24999926'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/jitse/spyder/spyder/plugins/ipythonconsole/widgets/main_widget.py", line 1542, in create_client_for_kernel
kernel_handler = KernelHandler.from_connection_file(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/jitse/spyder/spyder/plugins/ipythonconsole/utils/kernel_handler.py", line 437, in from_connection_file
kernel_client=cls.init_kernel_client(
^^^^^^^^^^^^^^^^^^^^^^^
File "/home/jitse/spyder/spyder/plugins/ipythonconsole/utils/kernel_handler.py", line 456, in init_kernel_client
raise RuntimeError(
RuntimeError: An error occurred while trying to load the kernel connection file. The error was:

[Errno 2] No such file or directory: '3ad02cfe‑e528𔂮f8f‑b831�f24999926'
```

This is using the master branch of both plugin and Spyder.

Looking at the file name, this may be an encoding issue.

**Comment by jitseniesen** [comment]
This issue appeared in #417.
