### ISSUE TITLE
Installation is failing if jupyter notebook isn't already installed

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder-notebook#54]
I experimented this error when runing `pip install .`

This is caused because `__init__` file is executed when importing  `__version__` in `setup.py`

```
Processing /home/rlaverde/code/spyder-notebook
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-_jv2fvz2-build/setup.py", line 17, in <module>
        from spyder_notebook import __version__
      File "/tmp/pip-_jv2fvz2-build/spyder_notebook/__init__.py", line 11, in <module>
        from spyder_notebook.notebookplugin import NotebookPlugin as PLUGIN_CLASS
      File "/tmp/pip-_jv2fvz2-build/spyder_notebook/notebookplugin.py", line 31, in <module>
        from .utils.nbopen import nbopen, NBServerError
      File "/tmp/pip-_jv2fvz2-build/spyder_notebook/utils/nbopen.py", line 16, in <module>
        from notebook import notebookapp
    ImportError: No module named 'notebook'
```

**Comment by ccordoba12** [comment]
Nice catch @rlaverde! Please send us a PR to fix this.

My proposal: Move this plugin version out of `__init__` to a `_version.py` file.
